model:
  gnn_type: 'ResGatedGCN'
  num_layers: 4
  hidden_channels: 256
  dropout: 0.01
  bias: True
  use_bn: True
  residual: True
  bidirection: True
  add_self_loops: True
  pos_enc: 'laplacian'
  pos_enc_dim: 16

train:
  batch_size: 2
  num_epochs: 4000
  lr: 2e-5
  weight_decay: 1e-12
  accelerator: 'gpu'

ckpt_path: 'src/predictor/ckpt/binding_site/atlas-flash.ckpt'