model:
  gnn_type: 'ResGatedGCN'
  num_layers: 4
  hidden_channels: 64
  dropout: 0.01
  bias: True
  use_bn: None
  residual: None
  bidirection: True
  add_self_loops: False
  pos_enc: False
  pos_enc_dim: 8

train:
  batch_size: 2
  num_epochs: 2000
  lr: 2e-5
  weight_decay: 1e-12
  accelerator: 'gpu'

ckpt_path: 'src/predictor/ckpt/binding_site/atlas-fga-GATv2.ckpt'