model:
  gnn_type: 'ResGatedGCN'
  num_layers: 4
  hidden_channels: 128
  dropout: 0.01
  bias: True
  use_bn: None
  residual: None
  bidirection: True
  add_self_loops: False
  pos_enc: 'laplacian'
  pos_enc_dim: 8
  global_pooling: 'max'

train:
  batch_size: 2
  num_epochs: 2000
  lr: 2e-4
  weight_decay: 1e-12
  accelerator: 'gpu'

ckpt_path: 'src/predictor/ckpt/concealer_size/atlas-fga-GATv2.ckpt'